import type {
  AdditionalHazardItem,
  ChecklistCategory,
  ChecklistItem,
  ChecklistMobileDraft,
  ChecklistPhoto,
  ChecklistReportMapping,
  ChecklistResult,
  ChecklistSession,
  ChecklistSessionDetailResponse,
  ChecklistTemplate,
  FindingCandidate,
  RiskReductionChecklistItem,
} from "../../packages/contracts/src";
import { sampleProject } from "./project-demo-data";

export const sampleChecklistTemplate: ChecklistTemplate = {
  id: "checklist-template-sample-001",
  name: "승강기 교체공사 표준 현장점검 체크리스트",
  description: "공사안전보건대장 이행점검 결과보고서용 기본 점검표",
  projectType: "elevator_replacement",
  documentType: "safety_health_ledger_inspection_report",
  version: "2026.1",
  status: "published",
  publishedAt: "2026-05-10T09:00:00+09:00",
  createdAt: "2026-05-10T09:00:00+09:00",
  updatedAt: "2026-05-10T09:00:00+09:00",
};

export const sampleChecklistCategories: ChecklistCategory[] = [
  { id: "checklist-category-common", templateId: sampleChecklistTemplate.id, key: "common", title: "공통", displayOrder: 1 },
  { id: "checklist-category-architecture", templateId: sampleChecklistTemplate.id, key: "architecture_civil", title: "건축·토목", displayOrder: 2 },
  { id: "checklist-category-machine", templateId: sampleChecklistTemplate.id, key: "construction_machine", title: "건설기계", displayOrder: 3 },
  { id: "checklist-category-risk", templateId: sampleChecklistTemplate.id, key: "risk_reduction", title: "위험성 감소대책", displayOrder: 4 },
  { id: "checklist-category-hazard", templateId: sampleChecklistTemplate.id, key: "additional_hazard", title: "추가 유해·위험요인", displayOrder: 5 },
];

export const sampleChecklistItems: ChecklistItem[] = [
  {
    id: "checklist-item-001",
    templateId: sampleChecklistTemplate.id,
    categoryId: "checklist-category-common",
    categoryKey: "common",
    discipline: null,
    title: "안전관리 계획 수립 및 이행 적정 여부",
    detail: "안전관리 계획서와 현장 적용 상태를 확인합니다.",
    reportLabel: "안전관리 계획 수립 및 이행",
    defaultApplicability: true,
    isRequired: true,
    findingRequiredWhen: "caution_or_bad",
    sourceSectionKey: "inspection_checklist",
    displayOrder: 1,
  },
  {
    id: "checklist-item-002",
    templateId: sampleChecklistTemplate.id,
    categoryId: "checklist-category-common",
    categoryKey: "common",
    discipline: null,
    title: "근로자 안전교육 및 개인보호구 착용상태",
    detail: "안전교육 이행과 보호구 지급상태를 확인합니다.",
    reportLabel: "근로자 안전교육 및 보호구",
    defaultApplicability: true,
    isRequired: true,
    findingRequiredWhen: "caution_or_bad",
    sourceSectionKey: "inspection_checklist",
    displayOrder: 2,
  },
  {
    id: "checklist-item-003",
    templateId: sampleChecklistTemplate.id,
    categoryId: "checklist-category-architecture",
    categoryKey: "architecture_civil",
    discipline: null,
    title: "전기 안전관리",
    detail: "가설전선 피복, 콘센트, 케이블릴 상태를 확인합니다.",
    reportLabel: "전기 안전관리",
    defaultApplicability: true,
    isRequired: true,
    findingRequiredWhen: "caution_or_bad",
    sourceSectionKey: "inspection_checklist",
    displayOrder: 3,
  },
  {
    id: "checklist-item-004",
    templateId: sampleChecklistTemplate.id,
    categoryId: "checklist-category-machine",
    categoryKey: "construction_machine",
    discipline: null,
    title: "건설기계 안전장치 상태",
    detail: "안전장치와 신호수 배치 상태를 확인합니다.",
    reportLabel: "건설기계 안전장치",
    defaultApplicability: true,
    isRequired: true,
    findingRequiredWhen: "caution_or_bad",
    sourceSectionKey: "inspection_checklist",
    displayOrder: 4,
  },
];

export const sampleChecklistSession: ChecklistSession = {
  id: "checklist-session-sample-001",
  projectId: sampleProject.id,
  inspectionRoundId: "round-sample-001",
  ownerPartyId: null,
  templateId: sampleChecklistTemplate.id,
  templateVersion: sampleChecklistTemplate.version,
  inspectorUserId: "user-inspector-001",
  inspectionDate: "2026-01-23",
  status: "in_progress",
  startedAt: "2026-05-10T09:00:00+09:00",
  completedAt: null,
  reviewedAt: null,
  lockedAt: null,
  createdAt: "2026-05-10T09:00:00+09:00",
  updatedAt: "2026-05-10T09:00:00+09:00",
  resultCount: 4,
  completedCount: 3,
  progressRate: 0.75,
};

export const sampleFindingCandidate: FindingCandidate = {
  id: "finding-candidate-sample-001",
  projectId: sampleProject.id,
  inspectionRoundId: "round-sample-001",
  sessionId: sampleChecklistSession.id,
  checklistResultId: "checklist-result-003",
  title: "전기 안전관리 보완 필요",
  detail: "가설전선 피복 보완과 케이블릴 정리 필요",
  riskType: "architecture_civil",
  requiredAction: "가설전선 피복 보완 및 케이블릴 정리",
  status: "candidate",
  convertedFindingId: null,
  dismissedReason: null,
  createdAt: "2026-05-10T09:00:00+09:00",
  updatedAt: "2026-05-10T09:00:00+09:00",
};

export const sampleChecklistResults: ChecklistResult[] = [
  {
    id: "checklist-result-001",
    sessionId: sampleChecklistSession.id,
    projectId: sampleProject.id,
    inspectionRoundId: "round-sample-001",
    checklistItemId: "checklist-item-001",
    result: "good",
    comment: null,
    reportComment: null,
    actionRequired: false,
    responsiblePartyId: null,
    dueDate: null,
    photoIds: [],
    findingCandidateId: null,
    findingId: null,
    reportMappingStatus: "mapped",
    createdAt: "2026-05-10T09:00:00+09:00",
    updatedAt: "2026-05-10T09:00:00+09:00",
    item: sampleChecklistItems[0],
  },
  {
    id: "checklist-result-002",
    sessionId: sampleChecklistSession.id,
    projectId: sampleProject.id,
    inspectionRoundId: "round-sample-001",
    checklistItemId: "checklist-item-002",
    result: "good",
    comment: null,
    reportComment: null,
    actionRequired: false,
    responsiblePartyId: null,
    dueDate: null,
    photoIds: [],
    findingCandidateId: null,
    findingId: null,
    reportMappingStatus: "mapped",
    createdAt: "2026-05-10T09:00:00+09:00",
    updatedAt: "2026-05-10T09:00:00+09:00",
    item: sampleChecklistItems[1],
  },
  {
    id: "checklist-result-003",
    sessionId: sampleChecklistSession.id,
    projectId: sampleProject.id,
    inspectionRoundId: "round-sample-001",
    checklistItemId: "checklist-item-003",
    result: "caution",
    comment: "가설전선 피복 보완과 케이블릴 정리 필요",
    reportComment: "현장 전기안전 관리 보완 필요",
    actionRequired: true,
    responsiblePartyId: "project-party-contractor-001",
    dueDate: "2026-01-25",
    photoIds: ["checklist-photo-sample-001"],
    findingCandidateId: sampleFindingCandidate.id,
    findingId: null,
    reportMappingStatus: "mapped",
    createdAt: "2026-05-10T09:00:00+09:00",
    updatedAt: "2026-05-10T09:00:00+09:00",
    item: sampleChecklistItems[2],
  },
  {
    id: "checklist-result-004",
    sessionId: sampleChecklistSession.id,
    projectId: sampleProject.id,
    inspectionRoundId: "round-sample-001",
    checklistItemId: "checklist-item-004",
    result: "not_checked",
    comment: null,
    reportComment: null,
    actionRequired: false,
    responsiblePartyId: null,
    dueDate: null,
    photoIds: [],
    findingCandidateId: null,
    findingId: null,
    reportMappingStatus: "not_mapped",
    createdAt: "2026-05-10T09:00:00+09:00",
    updatedAt: "2026-05-10T09:00:00+09:00",
    item: sampleChecklistItems[3],
  },
];

export const sampleRiskReductionItems: RiskReductionChecklistItem[] = [
  "가설분전반",
  "가설전선",
  "사다리",
  "말비계",
].map((fieldName, index) => ({
  id: `risk-reduction-sample-${index + 1}`,
  sessionId: sampleChecklistSession.id,
  no: index + 1,
  field: fieldName,
  workType: "승강기 교체 설치작업",
  contractorPlan: null,
  checkPoint: `${fieldName} 이행 확인`,
  result: index === 0 ? "good" : "not_checked",
  implementationStatus: index === 0 ? "implemented" : "not_checked",
  note: null,
  photoIds: [],
  createdAt: "2026-05-10T09:00:00+09:00",
  updatedAt: "2026-05-10T09:00:00+09:00",
}));

export const sampleAdditionalHazards: AdditionalHazardItem[] = [
  {
    id: "additional-hazard-sample-001",
    sessionId: sampleChecklistSession.id,
    no: 1,
    hazardDescription: "방우형 콘센트 덮개 파손 상태 확인 필요",
    contractorPlan: null,
    checkPoint: "현장 콘센트 방우 상태 확인",
    implementationStatus: "not_checked",
    note: null,
    photoIds: [],
    findingCandidateId: null,
    findingId: null,
    createdAt: "2026-05-10T09:00:00+09:00",
    updatedAt: "2026-05-10T09:00:00+09:00",
  },
];

export const sampleChecklistPhotos: ChecklistPhoto[] = [
  {
    id: "checklist-photo-sample-001",
    projectId: sampleProject.id,
    inspectionRoundId: "round-sample-001",
    sessionId: sampleChecklistSession.id,
    checklistResultId: "checklist-result-003",
    additionalHazardId: null,
    fileId: "file-asset-checklist-photo-001",
    fileName: "checklist_electrical_001.jpg",
    storagePath: "/리움미술관 승강기 교체공사/01_점검회차/01_체크리스트/checklist_electrical_001.jpg",
    caption: "가설전선 피복 보완 필요",
    createdAt: "2026-05-10T09:00:00+09:00",
    updatedAt: "2026-05-10T09:00:00+09:00",
  },
];

export const sampleChecklistReportMappings: ChecklistReportMapping[] = [
  {
    id: "checklist-report-mapping-sample-001",
    sessionId: sampleChecklistSession.id,
    documentId: null,
    sourceSectionKey: "inspection_checklist",
    reportLabel: "전기 안전관리",
    rowSummary: "전기 안전관리: caution",
    stale: false,
    createdAt: "2026-05-10T09:00:00+09:00",
    updatedAt: "2026-05-10T09:00:00+09:00",
  },
];

export const sampleChecklistMobileDraft: ChecklistMobileDraft = {
  id: "checklist-mobile-draft-sample-001",
  sessionId: sampleChecklistSession.id,
  clientVersion: 1,
  draftVersion: 1,
  payload: { offlineItems: ["checklist-item-004"] },
  conflictDetected: false,
  createdAt: "2026-05-10T09:00:00+09:00",
  updatedAt: "2026-05-10T09:00:00+09:00",
};

export function getSampleChecklistSessionDetail(sessionId: string): ChecklistSessionDetailResponse {
  const session = sessionId === sampleChecklistSession.id ? sampleChecklistSession : sampleChecklistSession;
  return {
    session,
    template: sampleChecklistTemplate,
    categories: sampleChecklistCategories,
    results: sampleChecklistResults,
    findingCandidates: [sampleFindingCandidate],
    riskReductionItems: sampleRiskReductionItems,
    additionalHazards: sampleAdditionalHazards,
    photos: sampleChecklistPhotos,
    reportMappings: sampleChecklistReportMappings,
    mobileDrafts: [sampleChecklistMobileDraft],
    auditLogs: [
      {
        id: "checklist-audit-sample-001",
        entityType: "checklist_session",
        entityId: session.id,
        action: "checklist-session.created",
        summary: "점검회차 체크리스트 세션이 생성되었습니다.",
        fieldNames: ["projectId", "inspectionRoundId", "templateId"],
        createdAt: "2026-05-10T09:00:00+09:00",
      },
    ],
    warnings: ["requiredChecklistItemsMissing"],
  };
}
