import type { ReportPayload } from '@saftysite/contracts';

export function buildDemoReport(reportId = 'demo-review'): ReportPayload {
  const isEmptyDraft = reportId === 'demo-review-empty';

  return {
    id: reportId,
    workspaceId: 'workspace-demo',
    status: 'draft_ready',
    currentSection: isEmptyDraft ? 'doc1' : 'doc7',
    wizardStep: 'workspace',
    photoStepBuckets: [
      {
        step: 'step1_overview',
        title: '현재 공정 또는 현장 전경',
        description: '현재 공정이나 현장 전경을 보여주는 필수 사진 1장입니다.',
        minRequired: 1,
        recommendedCount: 1,
        bucketRole: 'current_process_photo',
        uploadedPhotoIds: isEmptyDraft ? [] : ['photo-001', 'photo-003', 'photo-004'],
        representativePhotoId: isEmptyDraft ? null : 'photo-003',
        status: isEmptyDraft ? 'pending' : 'reviewed',
      },
      {
        step: 'step2_hazard',
        title: '현재 위험요인',
        description: '현재 위험요인이나 기인물을 보여주는 필수 사진 1장입니다.',
        minRequired: 1,
        recommendedCount: 1,
        bucketRole: 'current_hazard_photo',
        uploadedPhotoIds: isEmptyDraft ? [] : ['photo-002', 'photo-005', 'photo-006'],
        representativePhotoId: isEmptyDraft ? null : 'photo-002',
        status: isEmptyDraft ? 'pending' : 'reviewed',
      },
      {
        step: 'step3_followup',
        title: '이전 지적사항 확인',
        description: '이전 기술지도 지적사항 이행 여부를 확인할 선택 사진입니다.',
        minRequired: 0,
        recommendedCount: 1,
        bucketRole: 'previous_guidance_check_photo',
        uploadedPhotoIds: [],
        representativePhotoId: null,
        status: 'skipped',
      },
      {
        step: 'step4_support',
        title: '교육 및 지원활동',
        description: '교육이나 지원활동이 있으면 선택 사진으로 추가합니다.',
        minRequired: 0,
        recommendedCount: 1,
        bucketRole: 'education_support_photo',
        uploadedPhotoIds: [],
        representativePhotoId: null,
        status: 'skipped',
      },
      {
        step: 'step5_site_overview',
        title: '추가 현장 전경',
        description: '현장 전경을 보강할 추가 선택 사진입니다.',
        minRequired: 0,
        recommendedCount: 1,
        bucketRole: 'site_overview_photo',
        uploadedPhotoIds: [],
        representativePhotoId: null,
        status: 'skipped',
      },
    ],
    photoChecklistStatus: {
      step1OverviewComplete: !isEmptyDraft,
      step2HazardComplete: !isEmptyDraft,
      reviewReady: !isEmptyDraft,
      minimumSatisfied: !isEmptyDraft,
    },
    doc3PhotoCandidates: isEmptyDraft ? [] : ['photo-001', 'photo-003', 'photo-004'],
    doc7PhotoCandidates: isEmptyDraft ? [] : ['photo-002', 'photo-005', 'photo-006'],
    workspaceEntryMode: isEmptyDraft ? 'direct_reopen' : 'guided_photo_flow',
    doc11Doc12AutofillMode: 'resource_autofill',
    reportMeta: {
      workspaceName: '대한안전산업연구원 데모 워크스페이스',
      siteName: '세종 복합물류센터 신축현장',
      customerName: '대한건설 주식회사',
      guidanceAgencyName: '대한안전산업연구원',
      visitDate: '2026-04-29',
      drafterName: '홍길동 지도사',
      siteManagementNumber: 'MG-2026-041',
      businessStartNumber: 'BS-2026-041',
      constructionPeriod: '2026.02.01 ~ 2026.07.31',
      constructionAmount: '1,850,000,000원',
      siteManagerName: '김현장 소장',
      corporationRegistrationNumber: '110111-1234567',
      businessRegistrationNumber: '123-45-67890',
      licenseNumber: '건설업 제2026-01호',
      headquartersContact: '02-1234-5678',
      headquartersAddress: '세종특별자치시 한누리대로 100',
      constructionType: '건설공사',
      visitCount: '3',
      totalVisitCount: '6',
      previousImplementationStatus: 'implemented',
      notificationMethod: 'direct',
      notificationRecipientName: '이현장',
      otherNotificationMethod: '',
      progressRate: '67%',
      processSummary: '철골 조립 및 외장 패널 취부',
      workerCount: '24명',
      siteAddress: '세종시 집현동 100-1',
      siteContact: '010-1234-5678',
      reportPriceKrw: 3000,
    },
    reviewMeta: {
      reviewCompleted: false,
      reviewCompletedAt: null,
      responsibilityConfirmed: false,
      requiredFieldPaths: [
        'reportMeta.siteName',
        'reportMeta.customerName',
        'reportMeta.visitDate',
        'reportMeta.drafterName',
      ],
      reviewQueue: [
        {
          id: 'rq-reportMeta-siteAddress',
          section: 'reportMeta',
          field: 'siteAddress',
          fieldPath: 'reportMeta.siteAddress',
          label: '현장 주소',
          currentValue: '',
          suggestedValue: '',
          confidence: 0.18,
          reason: '사진만으로 확정할 수 없는 행정 필드',
          severity: 'warning',
          needsReview: true,
          status: 'pending',
          resolved: false,
          notes: '사진만으로 확정할 수 없는 행정 필드',
        },
        ...(isEmptyDraft
          ? [
              {
                id: 'rq-photoEvidence',
                section: 'other' as const,
                field: 'photoEvidence',
                fieldPath: 'photoEvidence',
                label: '사진 미첨부',
                currentValue: '',
                suggestedValue: '',
                confidence: 1,
                reason: '사진 미첨부 상태입니다.',
                severity: 'warning' as const,
                needsReview: true,
                status: 'pending' as const,
                resolved: false,
                notes: '사진 미첨부 상태입니다.',
              },
            ]
          : []),
        {
          id: 'rq-findingCandidates-0-improvementPlan',
          section: 'doc4',
          field: 'improvementPlan',
          fieldPath: 'findingCandidates[0].improvementPlan',
          label: '1번 지적 개선계획',
          currentValue: '',
          suggestedValue: '',
          confidence: 0.72,
          reason: '현장 장비 동선 확인 후 확정 필요',
          severity: 'warning',
          needsReview: true,
          status: 'reviewed',
          resolved: true,
          notes: '현장 장비 동선 확인 후 확정 필요',
        },
      ],
    },
    aiMeta: {
      pipelineVersion: 'v1-photo-first',
      lastRunId: 'airun-demo-01',
      lastRunStatus: 'succeeded',
      generatedAt: '2026-04-29T08:00:00.000Z',
      sourceMix: ['vision', 'ai_section', 'manual'],
    },
    photoObservations: isEmptyDraft
      ? []
      : [
        {
          photoAssetId: 'photo-003',
          photoRole: 'step1_overview',
          observedProcess: '외장 패널 취부',
          observedRisk: '향후 공정에서 외곽부 작업 시 추락 위험 검토 필요',
          observedProcessStructured: {
            majorProcess: '외부 마감공사',
            detailProcess: '외장 패널 취부',
            confidence: 0.76,
          },
          observedRiskStructured: {
            locationText: '외장 패널 취부 라인',
            accidentType: '추락',
            causativeAgent: '외곽 작업부 및 이동식 작업발판',
            hazardSummary: '향후 외장 패널 취부 작업 시 외곽부 추락 위험 검토 필요',
            recommendedActionKey: 'EXTERIOR_PANEL_EDGE_FALL',
            riskLevel: '중',
            confidence: 0.76,
          },
          rawAiNotes: '사진 기반 공정 분류 결과',
          confidence: 0.76,
          needsHumanReview: true,
        },
        {
          photoAssetId: 'photo-002',
          photoRole: 'step2_hazard',
          observedProcess: '현재 위험요인 점검',
          observedRisk: '인양 자재 하부 접근에 따른 충돌·낙하 위험',
          observedRiskStructured: {
            locationText: '타워크레인 자재 반입 구간',
            accidentType: '낙하',
            causativeAgent: '인양 자재 및 크레인',
            hazardSummary: '인양 자재 하부 접근에 따른 충돌·낙하 위험',
            recommendedActionKey: 'LIFTING_STRUCK_BY_LOAD',
            riskLevel: '중',
            confidence: 0.82,
          },
          rawAiNotes: '사진 기반 위험 관찰 결과',
          confidence: 0.82,
          needsHumanReview: true,
        },
      ],
    photoEvidence: isEmptyDraft
      ? []
      : [
          {
            photoAssetId: 'photo-001',
            category: 'site_overview',
            sourceStep: 'step1_overview',
            filename: 'overview-1.jpg',
            imageUrl: '',
            aiCategorySuggestion: 'site_overview',
            aiCategoryConfidence: 0.92,
            aiCategoryReason: 'step1 전경 묶음에서 수집된 대표 사진',
            sceneType: 'steel-frame',
            processType: '철골 조립',
            locationHint: '3층 외곽 작업구간',
            ppeSignals: ['안전모 미착용 인원 일부 확인'],
            hazardSignals: ['개구부 인접 작업', '임시 작업발판 간격 불균일'],
            accidentTypeCandidates: ['떨어짐'],
            causativeAgentCandidates: ['temporary_structure'],
            measurementContext: '',
            educationContext: '',
            activityContext: '',
            confidence: 0.91,
            notes: '고소작업 구간의 전경 사진',
          },
          {
            photoAssetId: 'photo-003',
            category: 'process',
            sourceStep: 'step1_overview',
            filename: 'process-1.jpg',
            imageUrl: '',
            aiCategorySuggestion: 'process',
            aiCategoryConfidence: 0.88,
            aiCategoryReason: 'step1 공정 사진으로 직접 업로드됨',
            sceneType: 'panel-installation',
            processType: '외장 패널 취부',
            locationHint: '외장 패널 취부 라인',
            ppeSignals: ['안전모 착용'],
            hazardSignals: ['작업반경 혼재', '고소작업 접근 필요'],
            accidentTypeCandidates: ['떨어짐'],
            causativeAgentCandidates: ['temporary_structure'],
            measurementContext: '',
            educationContext: '',
            activityContext: '',
            confidence: 0.84,
            notes: '현재 공정 설명용 사진',
          },
          {
            photoAssetId: 'photo-002',
            category: 'hazard',
            sourceStep: 'step2_hazard',
            filename: 'hazard-1.jpg',
            imageUrl: '',
            aiCategorySuggestion: 'hazard',
            aiCategoryConfidence: 0.9,
            aiCategoryReason: 'step2 위험요인 묶음으로 수집됨',
            sceneType: 'material-handling',
            processType: '자재 인양',
            locationHint: '타워크레인 자재 반입 구간',
            ppeSignals: ['형광조끼 착용'],
            hazardSignals: ['인양 반경 내 접근', '하부 통제 미흡'],
            accidentTypeCandidates: ['물체에 맞음', '부딪힘'],
            causativeAgentCandidates: ['lifting_load'],
            measurementContext: '',
            educationContext: '',
            activityContext: '',
            confidence: 0.86,
            notes: '중량물 하역 동선 확인 필요',
          },
          {
            photoAssetId: 'photo-005',
            category: 'hazard',
            sourceStep: 'step2_hazard',
            filename: 'hazard-2.jpg',
            imageUrl: '',
            aiCategorySuggestion: 'hazard',
            aiCategoryConfidence: 0.86,
            aiCategoryReason: 'step2 근거리 위험요인 사진',
            sceneType: 'opening-edge',
            processType: '작업발판 점검',
            locationHint: '개구부 인접 작업발판',
            ppeSignals: ['안전대 체결 여부 확인 필요'],
            hazardSignals: ['난간 미흡', '발판 고정 상태 재확인 필요'],
            accidentTypeCandidates: ['떨어짐'],
            causativeAgentCandidates: ['temporary_structure'],
            measurementContext: '',
            educationContext: '',
            activityContext: '',
            confidence: 0.89,
            notes: '추락 위험 지적용 근거리 사진',
          },
        ],
    findingCandidates: isEmptyDraft
      ? []
      : [
        {
          linkedPhotoIds: ['photo-001'],
          photoObservationIds: ['obs-hazard-1'],
          standardRiskRuleId: 'OPENING_FALL_COVER',
          source: 'AI_PHOTO_AND_RISK_LIBRARY',
          location: '3층 외곽 작업구간',
          hazardDescription: '개구부 인접 작업발판 고정 및 난간 설치 미흡에 따른 추락 위험',
          accidentType: '떨어짐',
            causativeAgentKey: 'temporary_structure',
            riskLevel: '상',
            improvementPlan: '작업발판 간격 및 고정상태를 재점검하고 개구부 난간과 덮개를 즉시 보강',
            emphasis: '고소작업 전 추락방지 설비 선조치 필요',
            legalReferenceCandidates: ['산업안전보건기준에 관한 규칙 제42조'],
            referenceMaterialCandidates: ['추락재해 예방 체크리스트'],
            confidence: 0.89,
            needsReview: true,
          },
        {
          linkedPhotoIds: ['photo-002'],
          photoObservationIds: ['obs-hazard-2'],
          standardRiskRuleId: 'LIFTING_STRUCK_BY_LOAD',
          source: 'AI_PHOTO_AND_RISK_LIBRARY',
          location: '타워크레인 자재 반입 구간',
          hazardDescription: '인양 하부 통제선 미흡으로 작업자 접근 시 낙하물 및 충돌 위험',
          accidentType: '물체에 맞음',
            causativeAgentKey: 'lifting_load',
            riskLevel: '중',
            improvementPlan: '인양 반경 출입통제와 신호수 배치를 명확히 하고 자재 유도 동선을 분리',
            emphasis: '하역 작업 시 접근 통제 우선',
            legalReferenceCandidates: ['산업안전보건기준에 관한 규칙 제146조'],
            referenceMaterialCandidates: ['중량물 취급 작업 안전수칙'],
            confidence: 0.82,
            needsReview: true,
          },
        ],
    sectionDrafts: {
      doc5: {
        progressOverview: '철골 조립과 외장 패널 취부가 병행되는 공정으로 고소작업 집중관리 필요',
        accidentTrend: '금회 추락과 낙하물 위험 중심의 지적 분포, 누적 추락 유형 재발 가능성 주의',
        findingCase: '개구부 인접 작업발판과 인양 하부 통제 미흡 사례가 확인되어 즉시 보완 필요',
        workEnvironmentRisk: '개구부, 중량물 이동, 작업반경 중첩으로 추락 위험요인과 충돌 위험 상존',
        futureProcessFocus: '향후 외장 패널 취부와 자재 반입 공정에서 추락 위험요인 및 낙하물 통제 재점검 필요',
      },
      doc7: [],
      doc8: [
        {
          processName: '외장 패널 취부',
          hazard: '외곽 작업 시 개구부 접근 및 추락 위험',
          countermeasure: '선시공 안전난간과 추락방지용 생명줄 상태를 매일 점검',
          confidence: 0.84,
          standardRiskRuleId: 'EXTERIOR_PANEL_EDGE_FALL',
          photoObservationIds: ['obs-overview-1'],
          needsReview: true,
          source: 'AI_PHOTO_AND_RISK_LIBRARY',
        },
      ],
      doc11: [
        {
          topic: '고소작업 전 TBM',
          content: '추락방지와 출입통제 교육안을 반영',
          attendeeCount: '24명',
          confidence: 0.64,
        },
      ],
      doc12: [
        {
          activityType: '현장 순회점검',
          content: '외곽부 추락방지시설과 인양구역 통제 상태 점검',
          confidence: 0.71,
        },
      ],
      doc13: [
        {
          title: '개구부 추락 재해 사례',
          summary: '임시 덮개 미고정 상태에서 작업 중 추락한 사고를 참고해 개구부 고정 점검을 강화',
          confidence: 0.76,
        },
      ],
      doc14: {
        title: '이번 주 안전정보',
        body: '추락재해와 중량물 낙하 사고 예방을 위해 개구부 방호와 인양구역 출입통제를 최우선 관리 항목으로 유지',
        confidence: 0.79,
      },
    },
    validationResult: {
      valid: false,
      blockingIssues: ['현장 주소와 담당자 연락처가 미입력 상태입니다.'],
      warnings: isEmptyDraft
        ? ['사진 미첨부 상태입니다.']
        : ['개선계획 2건 확인 필요'],
      reviewedFieldPaths: isEmptyDraft ? [] : ['findingCandidates[0].improvementPlan'],
    },
    fieldProvenance: isEmptyDraft
      ? []
      : [
          {
            fieldPath: 'reportMeta.siteName',
            source: 'DATA',
            sourceId: 'site:demo',
            confidence: 1,
            needsReview: false,
            note: '데모 현장 데이터',
          },
          {
            fieldPath: 'findingCandidates[0]',
            source: 'RISK_LIBRARY',
            sourceId: 'rule:OPENING_FALL_COVER',
            evidencePhotoIds: ['photo-001'],
            confidence: 0.89,
            needsReview: true,
            note: '표준 위험 라이브러리 기반 초안',
          },
        ],
    documentsCompat: {
      document2Overview: {
        siteName: '세종 복합물류센터 신축현장',
        processWorkContent: '철골 조립 및 외장 패널 취부',
      },
      document3Scenes: [],
      document4FollowUps: [
        {
          id: 'follow-up-demo-1',
          guidanceDate: '2026-04-10',
          confirmationDate: '2026-04-29',
          location: '개구부 주변',
          hazardDescription: '안전난간 미흡',
          actionRequired: '난간 및 덮개 설치',
          result: '확인 필요',
        },
      ],
      document5Summary: {
        text: 'sectionDrafts.doc5 요약 저장',
      },
      document6Measures: [],
      document7Findings: [],
      document8Plans: [],
      document9SafetyChecks: {},
      document10Measurements: [],
      document11EducationRecords: [],
      document12Activities: [],
      document13Cases: [],
      document14SafetyInfos: [],
    },
    createdAt: '2026-04-29T07:50:00.000Z',
    updatedAt: '2026-04-29T08:15:00.000Z',
  };
}
