import assert from 'node:assert/strict';
import test from 'node:test';

import { createReportInputSchema, reportPayloadSchema } from './schemas';

test('createReportInputSchema requires core metadata', () => {
  const result = createReportInputSchema.safeParse({
    workspace_id: 'workspace-1',
    site_id: 'site-1',
    visit_date: '2026-04-29',
    drafter_name: '홍길동',
  });

  assert.equal(result.success, true);
});

test('reportPayloadSchema allows empty photoObservations', () => {
  const result = reportPayloadSchema.safeParse({
    id: 'report-empty-observations',
    workspaceId: 'workspace-1',
    status: 'draft',
    currentSection: 'review',
    reportMeta: {
      workspaceName: 'Demo',
      siteName: '세종 현장',
      customerName: '대한건설',
      guidanceAgencyName: '대한안전산업연구원',
      visitDate: '2026-04-29',
      drafterName: '홍길동',
      previousImplementationStatus: 'not_applicable',
    },
    reviewMeta: {
      reviewCompleted: false,
      reviewCompletedAt: null,
      responsibilityConfirmed: false,
      requiredFieldPaths: [],
      reviewQueue: [],
    },
    aiMeta: {
      pipelineVersion: 'v1-photo-first',
      lastRunId: null,
      lastRunStatus: 'queued',
      generatedAt: null,
      sourceMix: ['manual'],
    },
    wizardStep: 'step1_overview',
    photoStepBuckets: [],
    photoChecklistStatus: {
      step1OverviewComplete: false,
      step2HazardComplete: false,
      reviewReady: false,
      minimumSatisfied: false,
    },
    doc3PhotoCandidates: [],
    doc7PhotoCandidates: [],
    workspaceEntryMode: 'guided_photo_flow',
    doc11Doc12AutofillMode: 'resource_autofill',
    photoEvidence: [],
    photoObservations: [],
    findingCandidates: [],
    sectionDrafts: {
      doc5: {
        progressOverview: '',
        accidentTrend: '',
        findingCase: '',
        workEnvironmentRisk: '',
        futureProcessFocus: '',
      },
      doc7: [],
      doc8: [],
      doc11: [],
      doc12: [],
      doc13: [],
      doc14: {
        title: '',
        body: '',
        confidence: 0,
      },
    },
    validationResult: {
      valid: false,
      blockingIssues: [],
      warnings: [],
      reviewedFieldPaths: [],
    },
    fieldProvenance: [],
    documentsCompat: {},
    createdAt: '2026-04-29T08:00:00.000Z',
    updatedAt: '2026-04-29T08:00:00.000Z',
  });

  assert.equal(result.success, true);
});

test('reportPayloadSchema validates photo-first payload shape', () => {
  const result = reportPayloadSchema.safeParse({
    id: 'report-1',
    workspaceId: 'workspace-1',
    status: 'draft_ready',
    currentSection: 'review',
    reportMeta: {
      workspaceName: 'Demo',
      siteName: '세종 현장',
      customerName: '대한건설',
      guidanceAgencyName: '대한안전산업연구원',
      visitDate: '2026-04-29',
      drafterName: '홍길동',
      progressRate: '67%',
      processSummary: '철골 조립',
      workerCount: '24명',
      siteAddress: '',
      siteContact: '',
      reportPriceKrw: 3000,
    },
    reviewMeta: {
      reviewCompleted: false,
      reviewCompletedAt: null,
      responsibilityConfirmed: false,
      requiredFieldPaths: ['reportMeta.siteName'],
      reviewQueue: [],
    },
    aiMeta: {
      pipelineVersion: 'v1-photo-first',
      lastRunId: null,
      lastRunStatus: 'queued',
      generatedAt: null,
      sourceMix: ['manual'],
    },
    wizardStep: 'step1_overview',
    photoStepBuckets: [
      {
        step: 'step1_overview',
        title: '공정 및 전경',
        description: '전경과 현재 공정을 설명하는 사진',
        minRequired: 1,
        recommendedCount: 1,
        bucketRole: 'current_process_photo',
        uploadedPhotoIds: ['photo-1'],
        representativePhotoId: 'photo-1',
        status: 'pending',
      },
      {
        step: 'step3_followup',
        title: '이전 지적사항 확인',
        description: '선택 사진',
        minRequired: 0,
        recommendedCount: 1,
        bucketRole: 'previous_guidance_check_photo',
        uploadedPhotoIds: [],
        representativePhotoId: null,
        status: 'skipped',
      },
    ],
    photoChecklistStatus: {
      step1OverviewComplete: false,
      step2HazardComplete: false,
      reviewReady: false,
      minimumSatisfied: false,
    },
    doc3PhotoCandidates: ['photo-1'],
    doc7PhotoCandidates: [],
    workspaceEntryMode: 'guided_photo_flow',
    doc11Doc12AutofillMode: 'resource_autofill',
    photoEvidence: [],
    photoObservations: [
      {
        id: 'obs-1',
        reportId: 'report-1',
        photoAssetId: 'photo-1',
        photoRole: 'step1_overview',
        observedProcess: '철골 조립',
        observedRisk: '향후 공정에서 추락 위험 검토 필요',
        observedProcessStructured: {
          majorProcess: '골조공사',
          detailProcess: '철골 조립',
          confidence: 0.72,
        },
        observedRiskStructured: {
          locationText: '3층 외곽 작업구간',
          accidentType: '추락',
          causativeAgent: '철골 작업발판 및 외곽 단부',
          hazardSummary: '향후 철골 조립 및 외곽부 작업 시 추락 위험 검토 필요',
          recommendedActionKey: 'STEEL_FRAME_FALL_PROTECTION',
          riskLevel: '중',
          confidence: 0.72,
        },
        rawAiNotes: '사진 기반 공정 분류 결과',
        confidence: 0.72,
        needsHumanReview: true,
        createdAt: '2026-04-29T08:00:00.000Z',
      },
    ],
    findingCandidates: [],
    sectionDrafts: {
      doc5: {
        progressOverview: '',
        accidentTrend: '',
        findingCase: '',
        workEnvironmentRisk: '',
        futureProcessFocus: '',
      },
      doc7: [],
      doc8: [],
      doc11: [],
      doc12: [],
      doc13: [],
      doc14: {
        title: '',
        body: '',
        confidence: 0.2,
      },
    },
    validationResult: {
      valid: false,
      blockingIssues: [],
      warnings: [],
      reviewedFieldPaths: [],
    },
    fieldProvenance: [
      {
        fieldPath: 'reportMeta.siteName',
        source: 'DATA',
        sourceId: 'site:site-1',
        confidence: 1,
        needsReview: false,
        note: '현장 DB 자동입력',
      },
    ],
    documentsCompat: {},
    createdAt: '2026-04-29T08:00:00.000Z',
    updatedAt: '2026-04-29T08:00:00.000Z',
  });

  assert.equal(result.success, true);
});

test('reportPayloadSchema validates extended guided photo buckets', () => {
  const result = reportPayloadSchema.safeParse({
    id: 'report-extended-buckets',
    workspaceId: 'workspace-1',
    status: 'draft_ready',
    currentSection: 'review',
    reportMeta: {
      workspaceName: 'Demo',
      siteName: '세종 현장',
      customerName: '대한건설',
      guidanceAgencyName: '대한안전산업연구원',
      visitDate: '2026-04-29',
      drafterName: '홍길동',
    },
    reviewMeta: {
      reviewCompleted: false,
      reviewCompletedAt: null,
      responsibilityConfirmed: false,
      requiredFieldPaths: [],
      reviewQueue: [],
    },
    aiMeta: {
      pipelineVersion: 'v1-photo-first',
      lastRunId: null,
      lastRunStatus: 'queued',
      generatedAt: null,
      sourceMix: ['manual'],
    },
    wizardStep: 'step2_hazard',
    photoStepBuckets: [
      {
        step: 'step1_overview',
        title: '현재 공정 또는 현장 전경',
        description: '필수 사진',
        minRequired: 1,
        recommendedCount: 1,
        bucketRole: 'current_process_photo',
        uploadedPhotoIds: ['photo-1'],
        representativePhotoId: 'photo-1',
        status: 'ready',
      },
      {
        step: 'step2_hazard',
        title: '현재 위험요인',
        description: '필수 사진',
        minRequired: 1,
        recommendedCount: 1,
        bucketRole: 'current_hazard_photo',
        uploadedPhotoIds: ['photo-2'],
        representativePhotoId: 'photo-2',
        status: 'ready',
      },
      {
        step: 'step3_followup',
        title: '이전 지적사항 확인',
        description: '선택 사진',
        minRequired: 0,
        recommendedCount: 1,
        bucketRole: 'previous_guidance_check_photo',
        uploadedPhotoIds: ['photo-3'],
        representativePhotoId: 'photo-3',
        status: 'reviewed',
      },
      {
        step: 'step4_support',
        title: '교육 및 지원활동',
        description: '선택 사진',
        minRequired: 0,
        recommendedCount: 1,
        bucketRole: 'education_support_photo',
        uploadedPhotoIds: [],
        representativePhotoId: null,
        status: 'skipped',
      },
      {
        step: 'step5_site_overview',
        title: '추가 현장 전경',
        description: '선택 사진',
        minRequired: 0,
        recommendedCount: 1,
        bucketRole: 'site_overview_photo',
        uploadedPhotoIds: ['photo-4'],
        representativePhotoId: 'photo-4',
        status: 'ready',
      },
    ],
    photoChecklistStatus: {
      step1OverviewComplete: true,
      step2HazardComplete: true,
      reviewReady: true,
      minimumSatisfied: true,
    },
    doc3PhotoCandidates: ['photo-1'],
    doc7PhotoCandidates: ['photo-2'],
    workspaceEntryMode: 'guided_photo_flow',
    doc11Doc12AutofillMode: 'resource_autofill',
    photoEvidence: [
      {
        photoAssetId: 'photo-3',
        category: 'followup',
        sourceStep: 'step3_followup',
        filename: 'followup.jpg',
        imageUrl: '',
        aiCategorySuggestion: 'followup',
        aiCategoryConfidence: 0,
        aiCategoryReason: '',
        sceneType: '',
        processType: '',
        locationHint: '',
        ppeSignals: [],
        hazardSignals: [],
        accidentTypeCandidates: [],
        causativeAgentCandidates: [],
        measurementContext: '',
        educationContext: '',
        activityContext: '',
        confidence: 0,
        notes: '',
      },
    ],
    photoObservations: [],
    findingCandidates: [],
    sectionDrafts: {
      doc5: {
        progressOverview: '',
        accidentTrend: '',
        findingCase: '',
        workEnvironmentRisk: '',
        futureProcessFocus: '',
      },
      doc7: [],
      doc8: [],
      doc11: [],
      doc12: [],
      doc13: [],
      doc14: {
        title: '',
        body: '',
        confidence: 0,
      },
    },
    validationResult: {
      valid: false,
      blockingIssues: [],
      warnings: [],
      reviewedFieldPaths: [],
    },
    fieldProvenance: [],
    documentsCompat: {},
    createdAt: '2026-04-29T08:00:00.000Z',
    updatedAt: '2026-04-29T08:00:00.000Z',
  });

  assert.equal(result.success, true);
});

test('reportPayloadSchema allows risk library metadata on findings and future plans', () => {
  const result = reportPayloadSchema.safeParse({
    id: 'report-risk-library',
    workspaceId: 'workspace-1',
    status: 'draft_ready',
    currentSection: 'review',
    reportMeta: {
      workspaceName: 'Demo',
      siteName: '세종 현장',
      customerName: '대한건설',
      guidanceAgencyName: '대한안전산업연구원',
      visitDate: '2026-04-29',
      drafterName: '홍길동',
    },
    reviewMeta: {
      reviewCompleted: false,
      reviewCompletedAt: null,
      responsibilityConfirmed: false,
      requiredFieldPaths: [],
      reviewQueue: [],
    },
    aiMeta: {
      pipelineVersion: 'v1-photo-first',
      lastRunId: null,
      lastRunStatus: 'queued',
      generatedAt: null,
      sourceMix: ['manual'],
    },
    wizardStep: 'workspace',
    photoStepBuckets: [],
    photoChecklistStatus: {
      step1OverviewComplete: true,
      step2HazardComplete: true,
      reviewReady: true,
      minimumSatisfied: true,
    },
    doc3PhotoCandidates: ['photo-1'],
    doc7PhotoCandidates: ['photo-2'],
    workspaceEntryMode: 'guided_photo_flow',
    doc11Doc12AutofillMode: 'resource_autofill',
    photoEvidence: [],
    photoObservations: [],
    findingCandidates: [
      {
        linkedPhotoIds: ['photo-2'],
        photoObservationIds: ['obs-hazard-1'],
        standardRiskRuleId: 'OPENING_FALL_COVER',
        source: 'AI_PHOTO_AND_RISK_LIBRARY',
        location: '개구부 주변',
        hazardDescription: '개구부 덮개 또는 안전난간 미흡으로 인한 추락 위험',
        accidentType: '추락',
        causativeAgentKey: 'temporary_structure',
        riskLevel: '상',
        improvementPlan:
          '개구부에는 견고한 덮개와 안전난간을 설치하고 작업 전 추락방지조치 상태를 재확인하실 것',
        emphasis: '□ 추후 이행여부 확인 필요',
        legalReferenceCandidates: ['산업안전보건기준에 관한 규칙'],
        referenceMaterialCandidates: ['개구부 추락방지 점검표'],
        confidence: 0.88,
        needsReview: true,
      },
    ],
    sectionDrafts: {
      doc5: {
        progressOverview: '',
        accidentTrend: '',
        findingCase: '',
        workEnvironmentRisk: '',
        futureProcessFocus: '',
      },
      doc7: [],
      doc8: [
        {
          processName: '외부 마감공사(외장 패널 취부)',
          hazard: '외장 패널 취부 과정에서 외곽부 접근과 작업발판 사용에 따른 추락 위험',
          countermeasure: '외곽부 방호조치 보강, 작업발판 고정, 안전대 사용점검 및 자재 적치구간 분리를 실시',
          note: '□ 추후 이행여부 확인 필요',
          evidencePhotoIds: ['photo-overview-1', 'photo-hazard-1'],
          confidence: 0.84,
          standardRiskRuleId: 'EXTERIOR_PANEL_EDGE_FALL',
          photoObservationIds: ['obs-overview-1'],
          needsReview: true,
          source: 'AI_PHOTO_AND_RISK_LIBRARY',
        },
      ],
      doc11: [],
      doc12: [],
      doc13: [],
      doc14: {
        title: '',
        body: '',
        confidence: 0,
      },
    },
    validationResult: {
      valid: false,
      blockingIssues: [],
      warnings: [],
      reviewedFieldPaths: [],
    },
    fieldProvenance: [],
    documentsCompat: {},
    createdAt: '2026-04-29T08:00:00.000Z',
    updatedAt: '2026-04-29T08:00:00.000Z',
  });

  assert.equal(result.success, true);
});

test('reportPayloadSchema allows extended review queue items', () => {
  const result = reportPayloadSchema.safeParse({
    id: 'report-review-queue',
    workspaceId: 'workspace-1',
    status: 'draft_ready',
    currentSection: 'review',
    reportMeta: {
      workspaceName: 'Demo',
      siteName: '세종 현장',
      customerName: '대한건설',
      guidanceAgencyName: '대한안전산업연구원',
      visitDate: '2026-04-29',
      drafterName: '홍길동',
    },
    reviewMeta: {
      reviewCompleted: false,
      reviewCompletedAt: null,
      responsibilityConfirmed: false,
      requiredFieldPaths: ['reportMeta.progressRate'],
      reviewQueue: [
        {
          id: 'rq-reportMeta-progressRate',
          section: 'reportMeta',
          field: 'progressRate',
          fieldPath: 'reportMeta.progressRate',
          label: '공정률',
          currentValue: '',
          suggestedValue: '',
          source: 'DATA',
          confidence: 0.1,
          reason: '행정 필수값이 비어 있어 사용자 확인이 필요합니다.',
          severity: 'required',
          needsReview: true,
          status: 'pending',
          evidencePhotoIds: [],
          resolved: false,
          notes: '행정 필수값이 비어 있어 사용자 확인이 필요합니다.',
        },
      ],
    },
    aiMeta: {
      pipelineVersion: 'v1-photo-first',
      lastRunId: null,
      lastRunStatus: 'queued',
      generatedAt: null,
      sourceMix: ['manual'],
    },
    wizardStep: 'workspace',
    photoStepBuckets: [],
    photoChecklistStatus: {
      step1OverviewComplete: false,
      step2HazardComplete: false,
      reviewReady: false,
      minimumSatisfied: false,
    },
    doc3PhotoCandidates: [],
    doc7PhotoCandidates: [],
    workspaceEntryMode: 'guided_photo_flow',
    doc11Doc12AutofillMode: 'resource_autofill',
    photoEvidence: [],
    photoObservations: [],
    findingCandidates: [],
    sectionDrafts: {
      doc5: {
        progressOverview: '',
        accidentTrend: '',
        findingCase: '',
        workEnvironmentRisk: '',
        futureProcessFocus: '',
      },
      doc7: [],
      doc8: [],
      doc11: [],
      doc12: [],
      doc13: [],
      doc14: {
        title: '',
        body: '',
        confidence: 0,
      },
    },
    validationResult: {
      valid: false,
      blockingIssues: [],
      warnings: [],
      reviewedFieldPaths: [],
    },
    fieldProvenance: [],
    documentsCompat: {},
    createdAt: '2026-04-29T08:00:00.000Z',
    updatedAt: '2026-04-29T08:00:00.000Z',
  });

  assert.equal(result.success, true);
});
