export const adminScreens = [
  {
    name: '01-admin-overview.png',
    path: '/admin?section=overview',
    readyText: '운영 개요',
  },
  {
    name: '02-admin-analytics.png',
    path: '/admin?section=analytics',
    readyText: '매출/실적 집계',
  },
  {
    name: '03-admin-headquarters.png',
    path: '/admin?section=headquarters',
    readyText: '사업장 목록',
  },
  {
    name: '04-admin-schedules.png',
    path: '/admin?section=schedules',
    readyText: '일정 / 캘린더',
  },
  {
    name: '05-admin-mailbox.png',
    path: '/admin?section=mailbox&box=inbox',
    readyText: '통합 메일함',
  },
] as const;

export const workerCalendarRows = [
  {
    id: 'schedule-1',
    siteId: 'site-1',
    siteName: '동부건설 안전센터 현장',
    headquarterId: 'hq-1',
    headquarterName: '동부건설',
    assigneeUserId: 'user-agent',
    assigneeName: '김지도',
    roundNo: 1,
    totalRounds: 8,
    plannedDate: '2026-04-08',
    actualVisitDate: '',
    selectionReasonLabel: '현장 요청',
    selectionReasonMemo: '공정 일정에 맞춰 방문',
    selectionConfirmedAt: '2026-04-01T09:00:00.000Z',
    selectionConfirmedByUserId: 'user-agent',
    selectionConfirmedByName: '김지도',
    status: 'planned',
    windowStart: '2026-04-01',
    windowEnd: '2026-04-15',
    linkedReportKey: '',
    isConflicted: false,
    isOutOfWindow: false,
    isOverdue: false,
    exceptionReasonCode: '',
    exceptionMemo: '',
  },
  {
    id: 'schedule-2',
    siteId: 'site-2',
    siteName: '한빛플랜트 신축 현장',
    headquarterId: 'hq-2',
    headquarterName: '한빛플랜트',
    assigneeUserId: 'user-agent',
    assigneeName: '김지도',
    roundNo: 2,
    totalRounds: 6,
    plannedDate: '2026-04-17',
    actualVisitDate: '',
    selectionReasonLabel: '정기 방문',
    selectionReasonMemo: '월간 기술지도 일정',
    selectionConfirmedAt: '2026-04-02T09:00:00.000Z',
    selectionConfirmedByUserId: 'user-agent',
    selectionConfirmedByName: '김지도',
    status: 'planned',
    windowStart: '2026-04-16',
    windowEnd: '2026-04-30',
    linkedReportKey: '',
    isConflicted: false,
    isOutOfWindow: false,
    isOverdue: false,
    exceptionReasonCode: '',
    exceptionMemo: '',
  },
  {
    id: 'schedule-3',
    siteId: 'site-1',
    siteName: '동부건설 안전센터 현장',
    headquarterId: 'hq-1',
    headquarterName: '동부건설',
    assigneeUserId: 'user-agent',
    assigneeName: '김지도',
    roundNo: 3,
    totalRounds: 8,
    plannedDate: '',
    actualVisitDate: '',
    selectionReasonLabel: '',
    selectionReasonMemo: '',
    selectionConfirmedAt: '',
    selectionConfirmedByUserId: '',
    selectionConfirmedByName: '',
    status: 'planned',
    windowStart: '2026-04-20',
    windowEnd: '2026-04-28',
    linkedReportKey: '',
    isConflicted: false,
    isOutOfWindow: false,
    isOverdue: false,
    exceptionReasonCode: '',
    exceptionMemo: '',
  },
] as const;
