import type {
  AppState,
  BadWorkplaceReport,
  DispatchState,
  Doc7Finding,
  PhotoAlbumItem,
  QuarterlyReport,
  ReviewState,
  SessionReport,
  Site,
  User,
} from './types';

const svgDataUrl = (label: string, accent: string) =>
  `data:image/svg+xml;utf8,${encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 420">
      <defs>
        <linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#fdf4df" />
          <stop offset="100%" stop-color="${accent}" />
        </linearGradient>
      </defs>
      <rect width="640" height="420" fill="url(#g)" rx="24" />
      <g fill="#102033" opacity="0.16">
        <circle cx="96" cy="86" r="72" />
        <circle cx="520" cy="318" r="96" />
      </g>
      <text x="48" y="210" font-size="44" font-family="Arial, sans-serif" fill="#102033" font-weight="700">${label}</text>
      <text x="48" y="260" font-size="22" font-family="Arial, sans-serif" fill="#38536f">reverse rebuild photo asset</text>
    </svg>`,
  )}`;

const review = (qualityStatus: ReviewState['qualityStatus'], note?: string): ReviewState => ({
  qualityStatus,
  note,
});

const dispatch = (partial: Partial<DispatchState>): DispatchState => ({
  sent: false,
  ...partial,
});

const buildFinding = (id: string, partial: Partial<Doc7Finding>): Doc7Finding => ({
  id,
  location: '',
  accidentType: '떨어짐',
  riskLevel: '중',
  causativeAgentKey: 'scaffold',
  hazardDescription: '',
  improvementPlan: '',
  improvementRequest: '',
  emphasis: '',
  legalReferenceTitle: '',
  referenceLawTitles: [],
  followUpStatus: 'pending',
  ...partial,
});

const users: User[] = [
  { id: 'u-admin-1', name: '박은지', role: 'admin', phone: '010-4200-1100' },
  { id: 'u-worker-1', name: '김도현', role: 'worker', phone: '010-2222-1111' },
  { id: 'u-worker-2', name: '이수민', role: 'worker', phone: '010-3333-2222' },
  { id: 'u-worker-3', name: '최정훈', role: 'worker', phone: '010-4444-3333' },
];

const sites: Site[] = [
  {
    id: 'site-alpha',
    headquarterId: 'hq-seoul',
    headquarterName: '서울 본부',
    siteName: '성수 스마트 리뉴얼',
    siteCode: 'SS-2026-01',
    managementNumber: 'A-110-2026',
    projectKind: '리모델링',
    siteAddress: '서울 성동구 연무장길 77',
    projectAmount: 1800000000,
    projectStartDate: '2026-01-10',
    projectEndDate: '2026-08-30',
    contractEndDate: '2026-08-30',
    lastVisitDate: '2026-04-10',
    guidanceOfficerId: 'u-worker-1',
    guidanceOfficerName: '김도현',
    inspectorName: '김도현',
    assignedUserIds: ['u-worker-1'],
    status: '운영중',
    siteManagerName: '홍성표',
    siteManagerContact: '010-7111-2121',
    adminSiteSnapshot: {
      headquarterName: '서울 본부',
      siteName: '성수 스마트 리뉴얼',
      siteAddress: '서울 성동구 연무장길 77',
      siteManagerName: '홍성표',
      siteManagerContact: '010-7111-2121',
      assigneeName: '김도현',
    },
    material: {
      quarterLabel: '2026년 1분기',
      educationMissing: 1,
      measurementMissing: 2,
      educationStatus: '교육 자료 1건 누락',
      measurementStatus: '계측 자료 2건 누락',
    },
  },
  {
    id: 'site-beta',
    headquarterId: 'hq-incheon',
    headquarterName: '경인지사',
    siteName: '송도 물류센터 증축',
    siteCode: 'SD-2026-04',
    managementNumber: 'B-220-2026',
    projectKind: '증축',
    siteAddress: '인천 연수구 센트럴로 98',
    projectAmount: 2450000000,
    projectStartDate: '2025-12-01',
    projectEndDate: '2026-05-20',
    contractEndDate: '2026-05-20',
    lastVisitDate: '2026-04-03',
    guidanceOfficerId: 'u-worker-2',
    guidanceOfficerName: '이수민',
    inspectorName: '이수민',
    assignedUserIds: ['u-worker-2'],
    status: '종료 임박',
    siteManagerName: '정하늘',
    siteManagerContact: '010-8123-1000',
    adminSiteSnapshot: {
      headquarterName: '경인지사',
      siteName: '송도 물류센터 증축',
      siteAddress: '인천 연수구 센트럴로 98',
      siteManagerName: '정하늘',
      siteManagerContact: '010-8123-1000',
      assigneeName: '이수민',
    },
    material: {
      quarterLabel: '2026년 1분기',
      educationMissing: 0,
      measurementMissing: 1,
      educationStatus: '교육 자료 충족',
      measurementStatus: '계측 자료 1건 누락',
    },
  },
  {
    id: 'site-gamma',
    headquarterId: 'hq-busan',
    headquarterName: '부산 지사',
    siteName: '해운대 주상복합 신축',
    siteCode: 'HD-2026-09',
    managementNumber: 'C-330-2026',
    projectKind: '신축',
    siteAddress: '부산 해운대구 마린시티2로 45',
    projectAmount: 5200000000,
    projectStartDate: '2026-02-15',
    projectEndDate: '2027-02-28',
    contractEndDate: '2027-02-28',
    lastVisitDate: '2026-03-27',
    guidanceOfficerId: 'u-worker-3',
    guidanceOfficerName: '최정훈',
    inspectorName: '최정훈',
    assignedUserIds: ['u-worker-3'],
    status: '준비중',
    siteManagerName: '강도윤',
    siteManagerContact: '010-5000-9999',
    adminSiteSnapshot: {
      headquarterName: '부산 지사',
      siteName: '해운대 주상복합 신축',
      siteAddress: '부산 해운대구 마린시티2로 45',
      siteManagerName: '강도윤',
      siteManagerContact: '010-5000-9999',
      assigneeName: '최정훈',
    },
    material: {
      quarterLabel: '2026년 1분기',
      educationMissing: 2,
      measurementMissing: 0,
      educationStatus: '교육 자료 2건 누락',
      measurementStatus: '계측 자료 충족',
    },
  },
];

const sessions: SessionReport[] = [
  {
    id: 'legacy:alpha-2026-01',
    reportKind: 'technical_guidance',
    siteId: 'site-alpha',
    siteName: '성수 스마트 리뉴얼',
    reportTitle: '1차 정기 기술지도',
    visitDate: '2026-03-12',
    reportNumber: 1,
    drafterName: '김도현',
    reviewerName: '박은지',
    approverName: '홍성표',
    updatedAt: '2026-04-12T09:20:00+09:00',
    lastAutosavedAt: '2026-04-12T09:05:00+09:00',
    progress: 86,
    status: 'draft',
    dispatchCompleted: false,
    summary: {
      overview: '철근 해체와 내부 마감이 병행되는 현장으로 작업 동선 충돌 위험이 큽니다.',
      siteScene: '동측 자재 적치구역과 서측 비계 통로의 혼재가 확인되었습니다.',
      previousGuidance: '지난 회차 지적사항 중 통로 적치물은 일부 개선되었습니다.',
      totalComment: '비계 작업과 양중 동선 분리를 최우선으로 요구했습니다.',
      deathFactors: '추락, 낙하물, 협착 위험이 동시에 존재합니다.',
      futureProcess: '4월 말까지 외장 비계 보강과 설비 반입이 예정되어 있습니다.',
      riskAssessment: 'TBM 기록은 있으나 세부 조치항목 이행 점검이 미흡합니다.',
      measurement: '분진 농도 측정 결과는 양호하나 소음 측정표 누락이 있습니다.',
      education: '신규 투입 인원 안전교육 서명부 누락 1건이 있습니다.',
      activity: '3월 재점검 완료 및 추후 지적사항 집중 관리 예정입니다.',
    },
    document7Findings: [
      buildFinding('finding-alpha-1', {
        photoUrl: svgDataUrl('비계 통로', '#eb8f56'),
        photoUrl2: svgDataUrl('자재 적치', '#9fd6b3'),
        location: '서측 비계 작업 통로',
        accidentType: '떨어짐',
        riskLevel: '상',
        causativeAgentKey: 'scaffold',
        hazardDescription: '작업 통로 옆 자재 적치로 이동 중 발 디딤 공간이 협소합니다.',
        improvementPlan: '비계 통로 1m 이상 확보 후 적치구역 분리',
        improvementRequest: '비계 통로 1m 이상 확보 후 적치구역 분리',
        emphasis: '추락방지 난간 재점검 필요',
        legalReferenceTitle: '산업안전보건기준에 관한 규칙 제13조',
        referenceLawTitles: ['산업안전보건기준에 관한 규칙 제13조'],
        followUpStatus: 'open',
        followUpNote: '개선 시작 전',
      }),
      buildFinding('finding-alpha-2', {
        photoUrl: svgDataUrl('양중 동선', '#69b4d1'),
        location: '북측 양중 반입구',
        accidentType: '부딪힘',
        riskLevel: '중',
        causativeAgentKey: 'traffic',
        hazardDescription: '양중 동선과 보행자 동선이 분리되지 않아 충돌 우려가 있습니다.',
        improvementPlan: '신호수 배치 및 동선 차단봉 설치',
        improvementRequest: '신호수 배치 및 동선 차단봉 설치',
        emphasis: '작업 반경 출입 통제',
        legalReferenceTitle: '산업안전보건기준에 관한 규칙 제38조',
        referenceLawTitles: ['산업안전보건기준에 관한 규칙 제38조'],
        followUpStatus: 'pending',
      }),
    ],
    review: review('issue', '비계 통로 개선 완료 후 재확인 필요'),
    dispatch: dispatch({
      sent: false,
      deadlineDate: '2026-03-19',
      phone: '010-7111-2121',
      message: '기술지도 보고서 발송 전 최종 확인이 필요합니다.',
    }),
  },
  {
    id: 'session-alpha-02',
    reportKind: 'technical_guidance',
    siteId: 'site-alpha',
    siteName: '성수 스마트 리뉴얼',
    reportTitle: '2차 정기 기술지도',
    visitDate: '2026-04-10',
    reportNumber: 2,
    drafterName: '김도현',
    reviewerName: '박은지',
    approverName: '홍성표',
    updatedAt: '2026-04-16T18:30:00+09:00',
    lastAutosavedAt: '2026-04-16T18:10:00+09:00',
    progress: 92,
    status: 'review',
    dispatchCompleted: true,
    dispatchCompletedAt: '2026-04-16T19:00:00+09:00',
    summary: {
      overview: '외장 비계 보강과 실내 설비 공사가 동시 진행 중입니다.',
      siteScene: '남측 적재함 주변 정리 상태는 양호하나 점검구역 표지 미흡합니다.',
      previousGuidance: '1차 지적사항 중 비계 통로 확보는 완료되었습니다.',
      totalComment: '작업지휘자 역할 분장과 출입통제 표지 보강이 필요합니다.',
      deathFactors: '추락과 부딪힘 위험은 완화되었으나 설비 반입구 관리 필요',
      futureProcess: '주간 양중 계획 수립 및 야간 자재 반입 축소 예정입니다.',
      riskAssessment: 'TBM 기록의 사진 첨부율이 개선되었습니다.',
      measurement: '소음/분진 측정표를 모두 확보했습니다.',
      education: '신규 투입 교육 서명부와 작업자 명단 일치 확인했습니다.',
      activity: '전회차 미이행 사항 해소 확인 및 2건 신규 지적 등록했습니다.',
    },
    document7Findings: [
      buildFinding('finding-alpha-3', {
        photoUrl: svgDataUrl('설비 반입구', '#a78ee6'),
        location: '1층 설비 반입구',
        accidentType: '부딪힘',
        riskLevel: '중',
        causativeAgentKey: 'opening',
        hazardDescription: '반입구 주변 출입 통제가 느슨해 작업자 동선과 겹칩니다.',
        improvementPlan: '출입통제 라인 재설치 및 안내판 보강',
        improvementRequest: '출입통제 라인 재설치 및 안내판 보강',
        emphasis: '신호수 상주',
        legalReferenceTitle: '산업안전보건기준에 관한 규칙 제21조',
        referenceLawTitles: ['산업안전보건기준에 관한 규칙 제21조'],
        followUpStatus: 'pending',
      }),
    ],
    review: review('ok', '보고서 품질 이상 없음'),
    dispatch: dispatch({
      sent: true,
      smsSent: true,
      phone: '010-7111-2121',
      message: '2차 정기 기술지도 보고서를 발송했습니다.',
      lastSentAt: '2026-04-16T19:00:00+09:00',
      deadlineDate: '2026-04-17',
    }),
  },
  {
    id: 'session-beta-01',
    reportKind: 'technical_guidance',
    siteId: 'site-beta',
    siteName: '송도 물류센터 증축',
    reportTitle: '3월 기술지도',
    visitDate: '2026-03-28',
    reportNumber: 3,
    drafterName: '이수민',
    reviewerName: '박은지',
    approverName: '정하늘',
    updatedAt: '2026-04-08T12:10:00+09:00',
    lastAutosavedAt: '2026-04-08T12:05:00+09:00',
    progress: 79,
    status: 'draft',
    summary: {
      overview: '외부 램프 구간 철골 조립이 집중되고 있습니다.',
      siteScene: '상하차 구역 안전통로는 있으나 임시 전선 정리가 필요합니다.',
      previousGuidance: '개구부 덮개는 일부 설치 완료되었습니다.',
      totalComment: '개구부 방호와 전선 정리 상태의 지속 점검이 필요합니다.',
      deathFactors: '개구부 추락과 감전 위험이 있습니다.',
      futureProcess: '철골 마감과 램프 구간 콘크리트 타설 예정입니다.',
      riskAssessment: '작업 전 위험성평가 참여율은 높으나 결과 공유 미흡',
      measurement: '조도 점검은 완료, 누전차단기 점검 기록 필요',
      education: '신규 협력사 인원 교육자료가 미제출 상태입니다.',
      activity: '이전 미이행 1건과 신규 1건을 동시에 추적합니다.',
    },
    document7Findings: [
      buildFinding('finding-beta-1', {
        photoUrl: svgDataUrl('개구부', '#f2c14f'),
        location: '2층 램프 개구부',
        accidentType: '떨어짐',
        riskLevel: '상',
        causativeAgentKey: 'opening',
        hazardDescription: '개구부 덮개가 고정되지 않아 작업자 추락 우려가 큽니다.',
        improvementPlan: '고정 덮개 재설치 및 경고표지 부착',
        improvementRequest: '고정 덮개 재설치 및 경고표지 부착',
        emphasis: '타설 전 재확인',
        legalReferenceTitle: '산업안전보건기준에 관한 규칙 제42조',
        referenceLawTitles: ['산업안전보건기준에 관한 규칙 제42조'],
        followUpStatus: 'open',
      }),
      buildFinding('finding-beta-2', {
        photoUrl: svgDataUrl('임시 전선', '#e36f6f'),
        location: '상하차 구역 우측 벽면',
        accidentType: '감전',
        riskLevel: '중',
        causativeAgentKey: 'electric',
        hazardDescription: '임시 전선이 바닥에 노출되어 이동 중 손상 위험이 있습니다.',
        improvementPlan: '전선 트레이 상향 및 케이블 보호대 설치',
        improvementRequest: '전선 트레이 상향 및 케이블 보호대 설치',
        emphasis: '누전차단기 점검 기록 유지',
        legalReferenceTitle: '산업안전보건기준에 관한 규칙 제323조',
        referenceLawTitles: ['산업안전보건기준에 관한 규칙 제323조'],
        followUpStatus: 'pending',
      }),
    ],
    review: review('issue', '전선 정리 개선 사진 필요'),
    dispatch: dispatch({
      sent: false,
      deadlineDate: '2026-04-04',
      phone: '010-8123-1000',
      message: '3월 기술지도 보고서 검토 후 발송 예정입니다.',
    }),
  },
  {
    id: 'session-gamma-01',
    reportKind: 'technical_guidance',
    siteId: 'site-gamma',
    siteName: '해운대 주상복합 신축',
    reportTitle: '착공 전 점검',
    visitDate: '2026-03-27',
    reportNumber: 1,
    drafterName: '최정훈',
    reviewerName: '박은지',
    approverName: '강도윤',
    updatedAt: '2026-03-29T16:00:00+09:00',
    lastAutosavedAt: '2026-03-29T15:40:00+09:00',
    progress: 64,
    status: 'draft',
    summary: {
      overview: '가설 사무실과 초기 장비 반입이 시작된 착공 초기 현장입니다.',
      siteScene: '울타리 설치는 완료되었으나 자재 적치선 표시는 미흡합니다.',
      previousGuidance: '착공 전 첫 회차로 누적 이력은 없습니다.',
      totalComment: '초기 출입통제와 장비 반입 동선 계획을 먼저 정리해야 합니다.',
      deathFactors: '중장비 접근과 가설전기 사용이 핵심 위험요인입니다.',
      futureProcess: '터파기와 파일 공정이 곧 시작됩니다.',
      riskAssessment: '계획 수립 단계',
      measurement: '측정 계획 수립 필요',
      education: '초기 교육 자료 준비 필요',
      activity: '현장 오픈 체크리스트와 병행 관리합니다.',
    },
    document7Findings: [
      buildFinding('finding-gamma-1', {
        photoUrl: svgDataUrl('가설 전기', '#69c78c'),
        location: '가설 사무실 외부',
        accidentType: '감전',
        riskLevel: '중',
        causativeAgentKey: 'electric',
        hazardDescription: '가설 전기함 주변 방수 조치가 부족합니다.',
        improvementPlan: '방수 커버 보강 및 접지 상태 점검',
        improvementRequest: '방수 커버 보강 및 접지 상태 점검',
        emphasis: '우천 전 조치',
        legalReferenceTitle: '산업안전보건기준에 관한 규칙 제302조',
        referenceLawTitles: ['산업안전보건기준에 관한 규칙 제302조'],
        followUpStatus: 'pending',
      }),
    ],
    review: review('unchecked'),
    dispatch: dispatch({
      sent: false,
      deadlineDate: '2026-04-03',
      phone: '010-5000-9999',
      message: '착공 전 점검 보고서 작성 중입니다.',
    }),
  },
];

const quarterlyReports: QuarterlyReport[] = [
  {
    id: 'quarterly-site-alpha-2026-Q1',
    reportKind: 'quarterly_report',
    siteId: 'site-alpha',
    title: '성수 스마트 리뉴얼 2026년 1분기 종합보고서',
    quarterKey: '2026-Q1',
    year: 2026,
    quarter: 1,
    periodStartDate: '2026-01-01',
    periodEndDate: '2026-03-31',
    generatedFromSessionIds: ['legacy:alpha-2026-01'],
    explicitSelection: false,
    lastCalculatedAt: '2026-04-12T10:00:00+09:00',
    drafter: '김도현',
    reviewer: '박은지',
    approver: '홍성표',
    updatedAt: '2026-04-12T10:30:00+09:00',
    siteSnapshot: sites[0].adminSiteSnapshot,
    implementationRows: [
      {
        id: 'impl-alpha-1',
        sourceSessionId: 'legacy:alpha-2026-01',
        reportTitle: '1차 정기 기술지도',
        guidanceDate: '2026-03-12',
        findingCount: 2,
        completionStatus: '1건 미이행',
      },
    ],
    accidentStats: [
      { label: '떨어짐', value: 1 },
      { label: '부딪힘', value: 1 },
    ],
    causativeStats: [
      { label: '비계/발판', value: 1 },
      { label: '동선 충돌', value: 1 },
    ],
    futurePlans: ['외장 비계 보강 완료 후 4월 말 재점검', '양중 동선 분리 계획 운영'],
    majorMeasures: ['비계 통로 1m 확보', '신호수 배치 및 차단봉 설치'],
    opsAssetId: 'ops-spring',
    opsAssetTitle: '봄철 안전 캠페인',
    opsAssetDescription: '추락방지와 이동통로 정리에 초점을 둔 분기 캠페인',
    opsAssetPreviewUrl: svgDataUrl('OPS Campaign', '#87b9f6'),
    review: review('ok', '분기 반영 완료'),
    dispatch: dispatch({
      sent: false,
      deadlineDate: '2026-04-20',
      phone: '010-7111-2121',
      message: '1분기 종합보고서 발송 대기',
    }),
    status: 'draft',
    controllerReview: '주요 조치사항 요약 적정',
  },
  {
    id: 'quarterly-site-beta-2026-Q1',
    reportKind: 'quarterly_report',
    siteId: 'site-beta',
    title: '송도 물류센터 증축 2026년 1분기 종합보고서',
    quarterKey: '2026-Q1',
    year: 2026,
    quarter: 1,
    periodStartDate: '2026-01-01',
    periodEndDate: '2026-03-31',
    generatedFromSessionIds: ['session-beta-01'],
    explicitSelection: true,
    lastCalculatedAt: '2026-04-08T13:00:00+09:00',
    drafter: '이수민',
    reviewer: '박은지',
    approver: '정하늘',
    updatedAt: '2026-04-08T13:10:00+09:00',
    siteSnapshot: sites[1].adminSiteSnapshot,
    implementationRows: [
      {
        id: 'impl-beta-1',
        sourceSessionId: 'session-beta-01',
        reportTitle: '3월 기술지도',
        guidanceDate: '2026-03-28',
        findingCount: 2,
        completionStatus: '2건 추적 중',
      },
    ],
    accidentStats: [
      { label: '떨어짐', value: 1 },
      { label: '감전', value: 1 },
    ],
    causativeStats: [
      { label: '개구부', value: 1 },
      { label: '전기', value: 1 },
    ],
    futurePlans: ['개구부 고정 덮개 설치 확인', '임시 전선 상향 정리'],
    majorMeasures: ['개구부 고정 덮개 재설치', '케이블 보호대 설치'],
    opsAssetId: 'ops-ramp',
    opsAssetTitle: '개구부 집중 관리',
    opsAssetDescription: '철골 및 램프 공정 전용 체크포인트',
    opsAssetPreviewUrl: svgDataUrl('Ramp OPS', '#f4a45f'),
    review: review('issue', '미발송 장기화로 우선 관리 필요'),
    dispatch: dispatch({
      sent: false,
      deadlineDate: '2026-04-12',
      phone: '010-8123-1000',
      message: '1분기 종합보고서 발송 전 검토 중',
    }),
    status: 'review',
    controllerReview: '지연 신호',
  },
];

const badWorkplaceReports: BadWorkplaceReport[] = [
  {
    id: 'bad-site-beta-2026-03',
    reportKind: 'bad_workplace',
    siteId: 'site-beta',
    title: '송도 물류센터 증축 2026-03 고위험 취약 현장 통보서',
    reportMonth: '2026-03',
    status: 'draft',
    dispatchCompleted: false,
    controllerReview: '개구부 미이행 지속',
    sourceMode: 'previous_unresolved',
    sourceSessionId: 'session-beta-01',
    sourceFindingIds: ['finding-beta-1'],
    guidanceDate: '2026-03-28',
    confirmationDate: '2026-04-05',
    progressRate: 40,
    implementationCount: 1,
    reporterUserId: 'u-worker-2',
    reporterName: '이수민',
    receiverName: '정하늘',
    assigneeContact: '010-3333-2222',
    agencyName: '한국종합안전',
    agencyRepresentative: '장정규',
    notificationDate: '2026-04-05',
    attachmentDescription: '개구부 사진 1건 첨부',
    siteSnapshot: sites[1].adminSiteSnapshot,
    violations: [
      {
        id: 'violation-beta-1',
        sourceFindingId: 'finding-beta-1',
        legalReference: '산업안전보건기준에 관한 규칙 제42조',
        hazardFactor: '개구부 덮개 미고정',
        improvementMeasure: '고정 덮개 재설치 및 경고표지 부착',
        guidanceDate: '2026-03-28',
        nonCompliance: '이전 지적사항이 미이행 상태로 유지되고 있습니다.',
        confirmationDate: '2026-04-05',
        accidentType: '떨어짐',
        causativeAgentKey: 'opening',
      },
    ],
    updatedAt: '2026-04-09T11:00:00+09:00',
    review: review('issue', '즉시 통보 필요'),
    dispatch: dispatch({
      sent: false,
      deadlineDate: '2026-04-10',
      phone: '010-8123-1000',
      message: '고위험 취약 현장 통보서 발송 예정',
    }),
  },
  {
    id: 'bad-site-alpha-2026-04',
    reportKind: 'bad_workplace',
    siteId: 'site-alpha',
    title: '성수 스마트 리뉴얼 2026-04 고위험 취약 현장 통보서',
    reportMonth: '2026-04',
    status: 'draft',
    dispatchCompleted: true,
    controllerReview: '당회차 신규 위험 통보 완료',
    sourceMode: 'current_new_hazard',
    sourceSessionId: 'session-alpha-02',
    sourceFindingIds: ['finding-alpha-3'],
    guidanceDate: '2026-04-10',
    confirmationDate: '2026-04-16',
    progressRate: 100,
    implementationCount: 1,
    reporterUserId: 'u-worker-1',
    reporterName: '김도현',
    receiverName: '홍성표',
    assigneeContact: '010-2222-1111',
    agencyName: '한국종합안전',
    agencyRepresentative: '장정규',
    notificationDate: '2026-04-16',
    attachmentDescription: '설비 반입구 사진 첨부',
    siteSnapshot: sites[0].adminSiteSnapshot,
    violations: [
      {
        id: 'violation-alpha-1',
        sourceFindingId: 'finding-alpha-3',
        legalReference: '산업안전보건기준에 관한 규칙 제21조',
        hazardFactor: '반입구 출입 통제 미흡',
        improvementMeasure: '출입통제 라인 재설치 및 안내판 보강',
        guidanceDate: '2026-04-10',
        nonCompliance: '당회차 신규 위험요인으로 즉시 개선이 요구됩니다.',
        confirmationDate: '2026-04-16',
        accidentType: '부딪힘',
        causativeAgentKey: 'opening',
      },
    ],
    updatedAt: '2026-04-16T18:40:00+09:00',
    review: review('ok', '발송 완료'),
    dispatch: dispatch({
      sent: true,
      manualChecked: true,
      phone: '010-7111-2121',
      message: '고위험 취약 현장 통보서를 발송했습니다.',
      lastSentAt: '2026-04-16T18:45:00+09:00',
      deadlineDate: '2026-04-17',
    }),
  },
];

const photos: PhotoAlbumItem[] = [
  {
    id: 'photo-alpha-1',
    siteId: 'site-alpha',
    siteName: '성수 스마트 리뉴얼',
    headquarterId: 'hq-seoul',
    headquarterName: '서울 본부',
    previewUrl: svgDataUrl('Album Alpha 1', '#eb8f56'),
    downloadUrl: svgDataUrl('Album Alpha 1', '#eb8f56'),
    fileName: 'alpha-scaffold.jpg',
    contentType: 'image/jpeg',
    sizeBytes: 420000,
    capturedAt: '2026-04-10T13:10:00+09:00',
    createdAt: '2026-04-10T13:30:00+09:00',
    uploadedByUserId: 'u-worker-1',
    uploadedByName: '김도현',
    gpsLatitude: 37.545,
    gpsLongitude: 127.055,
    sourceKind: 'album_upload',
  },
  {
    id: 'photo-alpha-legacy',
    siteId: 'site-alpha',
    siteName: '성수 스마트 리뉴얼',
    headquarterId: 'hq-seoul',
    headquarterName: '서울 본부',
    previewUrl: svgDataUrl('Legacy Alpha', '#69b4d1'),
    downloadUrl: svgDataUrl('Legacy Alpha', '#69b4d1'),
    fileName: 'legacy-alpha-doc7.jpg',
    contentType: 'image/jpeg',
    sizeBytes: 380000,
    capturedAt: '2026-03-12T11:30:00+09:00',
    createdAt: '2026-04-01T10:00:00+09:00',
    sourceKind: 'legacy_import',
    sourceReportKey: 'legacy:alpha-2026-01',
    sourceDocumentKey: 'doc7',
    sourceSlotKey: 'photoUrl',
    sourceReportTitle: '1차 정기 기술지도',
  },
  {
    id: 'photo-beta-1',
    siteId: 'site-beta',
    siteName: '송도 물류센터 증축',
    headquarterId: 'hq-incheon',
    headquarterName: '경인지사',
    previewUrl: svgDataUrl('Album Beta 1', '#f2c14f'),
    downloadUrl: svgDataUrl('Album Beta 1', '#f2c14f'),
    fileName: 'beta-opening.jpg',
    contentType: 'image/jpeg',
    sizeBytes: 520000,
    capturedAt: '2026-03-28T09:05:00+09:00',
    createdAt: '2026-03-28T09:20:00+09:00',
    uploadedByUserId: 'u-worker-2',
    uploadedByName: '이수민',
    sourceKind: 'album_upload',
  },
  {
    id: 'photo-beta-legacy',
    siteId: 'site-beta',
    siteName: '송도 물류센터 증축',
    headquarterId: 'hq-incheon',
    headquarterName: '경인지사',
    previewUrl: svgDataUrl('Legacy Beta', '#e36f6f'),
    downloadUrl: svgDataUrl('Legacy Beta', '#e36f6f'),
    fileName: 'legacy-beta-doc7.jpg',
    contentType: 'image/jpeg',
    sizeBytes: 500000,
    capturedAt: '2026-03-28T10:00:00+09:00',
    createdAt: '2026-04-01T11:00:00+09:00',
    sourceKind: 'legacy_import',
    sourceReportKey: 'session-beta-01',
    sourceDocumentKey: 'doc7',
    sourceSlotKey: 'photoUrl',
    sourceReportTitle: '3월 기술지도',
  },
  {
    id: 'photo-gamma-1',
    siteId: 'site-gamma',
    siteName: '해운대 주상복합 신축',
    headquarterId: 'hq-busan',
    headquarterName: '부산 지사',
    previewUrl: svgDataUrl('Album Gamma 1', '#69c78c'),
    downloadUrl: svgDataUrl('Album Gamma 1', '#69c78c'),
    fileName: 'gamma-electric.jpg',
    contentType: 'image/jpeg',
    sizeBytes: 310000,
    capturedAt: '2026-03-27T14:10:00+09:00',
    createdAt: '2026-03-27T14:25:00+09:00',
    uploadedByUserId: 'u-worker-3',
    uploadedByName: '최정훈',
    sourceKind: 'album_upload',
  },
];

export const initialAppState: AppState = {
  currentUserId: 'u-admin-1',
  users,
  sites,
  schedules: [
    {
      id: 'schedule-alpha-1',
      siteId: 'site-alpha',
      siteName: '성수 스마트 리뉴얼',
      headquarterId: 'hq-seoul',
      headquarterName: '서울 본부',
      roundNo: 3,
      totalRounds: 8,
      plannedDate: '2026-04-24',
      windowStart: '2026-04-22',
      windowEnd: '2026-04-28',
      assigneeUserId: 'u-worker-1',
      assigneeName: '김도현',
      status: 'selected',
      selectionConfirmedAt: '2026-04-16T10:00:00+09:00',
      selectionConfirmedByName: '김도현',
      selectionReasonLabel: '현장 요청',
      selectionReasonMemo: '자재 반입 일정에 맞춰 24일 방문',
    },
    {
      id: 'schedule-alpha-2',
      siteId: 'site-alpha',
      siteName: '성수 스마트 리뉴얼',
      headquarterId: 'hq-seoul',
      headquarterName: '서울 본부',
      roundNo: 4,
      totalRounds: 8,
      windowStart: '2026-05-12',
      windowEnd: '2026-05-18',
      assigneeUserId: 'u-worker-1',
      assigneeName: '김도현',
      status: 'unselected',
    },
    {
      id: 'schedule-alpha-3',
      siteId: 'site-alpha',
      siteName: '성수 스마트 리뉴얼',
      headquarterId: 'hq-seoul',
      headquarterName: '서울 본부',
      roundNo: 2,
      totalRounds: 8,
      plannedDate: '2026-04-10',
      actualVisitDate: '2026-04-10',
      windowStart: '2026-04-08',
      windowEnd: '2026-04-12',
      assigneeUserId: 'u-worker-1',
      assigneeName: '김도현',
      status: 'completed',
      selectionReasonLabel: '정기 점검',
      selectionReasonMemo: '분기 전 최종 점검',
    },
    {
      id: 'schedule-beta-1',
      siteId: 'site-beta',
      siteName: '송도 물류센터 증축',
      headquarterId: 'hq-incheon',
      headquarterName: '경인지사',
      roundNo: 4,
      totalRounds: 6,
      plannedDate: '2026-04-18',
      windowStart: '2026-04-17',
      windowEnd: '2026-04-22',
      assigneeUserId: 'u-worker-2',
      assigneeName: '이수민',
      status: 'selected',
      selectionReasonLabel: '우선 점검',
      selectionReasonMemo: '개구부 개선 확인',
      isOverdue: true,
    },
    {
      id: 'schedule-beta-2',
      siteId: 'site-beta',
      siteName: '송도 물류센터 증축',
      headquarterId: 'hq-incheon',
      headquarterName: '경인지사',
      roundNo: 5,
      totalRounds: 6,
      windowStart: '2026-05-06',
      windowEnd: '2026-05-12',
      assigneeUserId: 'u-worker-2',
      assigneeName: '이수민',
      status: 'unselected',
      isConflicted: true,
    },
    {
      id: 'schedule-beta-3',
      siteId: 'site-beta',
      siteName: '송도 물류센터 증축',
      headquarterId: 'hq-incheon',
      headquarterName: '경인지사',
      roundNo: 3,
      totalRounds: 6,
      plannedDate: '2026-03-28',
      actualVisitDate: '2026-03-28',
      windowStart: '2026-03-25',
      windowEnd: '2026-03-31',
      assigneeUserId: 'u-worker-2',
      assigneeName: '이수민',
      status: 'completed',
      selectionReasonLabel: '정기 점검',
      selectionReasonMemo: '월말 점검',
    },
    {
      id: 'schedule-gamma-1',
      siteId: 'site-gamma',
      siteName: '해운대 주상복합 신축',
      headquarterId: 'hq-busan',
      headquarterName: '부산 지사',
      roundNo: 1,
      totalRounds: 10,
      plannedDate: '2026-04-20',
      windowStart: '2026-04-18',
      windowEnd: '2026-04-24',
      assigneeUserId: 'u-worker-3',
      assigneeName: '최정훈',
      status: 'selected',
      selectionReasonLabel: '착공 초기',
      selectionReasonMemo: '터파기 전 점검',
    },
    {
      id: 'schedule-gamma-2',
      siteId: 'site-gamma',
      siteName: '해운대 주상복합 신축',
      headquarterId: 'hq-busan',
      headquarterName: '부산 지사',
      roundNo: 2,
      totalRounds: 10,
      windowStart: '2026-05-14',
      windowEnd: '2026-05-20',
      assigneeUserId: 'u-worker-3',
      assigneeName: '최정훈',
      status: 'unselected',
    },
  ],
  sessions,
  quarterlyReports,
  badWorkplaceReports,
  photos,
};

export const createInitialState = (): AppState => JSON.parse(JSON.stringify(initialAppState)) as AppState;

export const cloneAppState = (state: AppState): AppState => JSON.parse(JSON.stringify(state)) as AppState;

